name: Geometric Weather CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - ".editorconfig"
      - "fastlane/*"
      - "release/*"
      - "work/*"
      - "LICENSE"
      - "README.md"
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean assembleDebug   

      - name: Create APK directory
        run: mkdir -p $GITHUB_WORKSPACE/app/build/outputs/apk/debug/

      - name: Copy APK to directory
        run: cp $GITHUB_WORKSPACE/app/build/outputs/apk/debug/*.apk $GITHUB_WORKSPACE/app/build/outputs/apk/debug/app-debug.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/
